spring:
  application:
    name: pessoa
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
    consumer:
      group-id: pessoa-reply-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/pessoa_db?currentSchema=pessoa_db
    username: postgresql
    password: postgresql
  jpa:
    properties:
      hibernate:
        default_schema: pessoa_db
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    schemas: pessoa_db

server:
  port: 8090
  servlet:
        context-path: /api


# Configurações específicas para ReplyingKafkaTemplate
kafka:
  reply:
    topic: consultar-serasa-response
    timeout: 10000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.connections.pooling: ERROR
    org.apache.kafka: INFO
