spring:
  application:
    name: microsservico-serasa
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3

server:
  port: 8070

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.connections.pooling: ERROR
    org.apache.kafka: INFO
