spring:
  application:
    name: microsservico-serasa
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
    consumer:
      group-id: serasa-group
      auto-offset-reset: earliest

server:
  port: 8070

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.apache.kafka: INFO
