spring:
  application:
    name: microsservico-log
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/log_db?currentSchema=log_db
    username: postgresql
    password: postgresql
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    default-schema: log_db
    schemas: log_db
  jpa:
    properties:
      hibernate:
        default_schema: log_db

  kafka:
    bootstrap-servers: localhost:9092  # Servidor Kafka
    consumer:
      group-id: log-service-group  # Grupo do consumer
      auto-offset-reset: earliest

server:
  port: 8060

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: DEBUG  # Log detalhado para Spring Kafka
    org.hibernate.orm.connections.pooling: ERROR
    org.hibernate.SQL: DEBUG  # Log das queries SQL